language: node_js
node_js:
  - stable
cache:
  yarn: true

before_deploy: yarn build
deploy:
  provider: npm
  email: dustinschau@gmail.com
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
